server:
  servlet:
    context-path: /v1/sweet-stock/

spring:
  mail:
    default-encodig: UTF-8
    host: smtp.gmail.com
    port: 587
    username: sweet.stock.contato@gmail.com
    password: uklnqcdopznacnmh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-231-82-226.compute-1.amazonaws.com:5432/d8to2suiio4k8u?user=vvfqmakigpkewn&password=0e91cfc0dc5550a6805fa33365ba91d54c195b4a83c2c3ac02a0b5094a485267
    username: vvfqmakigpkewn
    password: 0e91cfc0dc5550a6805fa33365ba91d54c195b4a83c2c3ac02a0b5094a485267
  jpa:
    #    hibernate.ddl-auto: update
    generate-ddl: true
    #    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

