server:
  servlet:
    context-path: /v1/sweet-stock/

spring:
  mail:
    default-encodig: UTF-8
    host: smtp.gmail.com
    port: 587
    username: sweet.stock.contato@gmail.com
    password: uklnqcdopznacnmh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sweetstock
    username: sweetstock
    password: sweetstock
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false