server:
  servlet:
    context-path: /v1/sweet-stock/

spring:
  mail:
    default-encodig: UTF-8
    host: smtp.gmail.com
    port: 587
    username: sweet.stock.contato@gmail.com
    password: uklnqcdopznacnmh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sweetstock