server:
  servlet:
    context-path: /v1/sweet-stock/

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sweetstock
    username: sweetstock
    password: sweetstock
  jpa:
    hibernate.ddl-auto: create-drop
#    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false