server:
  servlet:
    context-path: /v1/sweet-stock/

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: abnerlucasdarochasantos@gmail.com
    password: xzcwxemkmknkurnh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sweetstock
    username: sweetstock
    password: sweetstock
  jpa:
    hibernate.ddl-auto: create-drop
#    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false